---
title: "HW07 Part 1: Complete the sections"
author: "Cody Grainger"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r}
library("tidyverse")
library("GGally")
library("devtools")
```

```{r}
devtools::install_github("thomasp85/patchwork", force = TRUE)
library("patchwork")
```
```{r}
#Keep getting weird working directory errors, I temporarily set it manually here just to get the raw data into a "sparrows"
setwd("C:/Users/bacon/Documents/bi485/grainger_cody/data")
sparrows_raw <- read_tsv("sparrows.txt")
```

```{r}
#View imported tsv
View(sparrows_raw)
```

```{r}
sparrows <- sparrows_raw %>%
  mutate(box_group = "Sparrows",
         row_order = 1:nrow(.))

View(sparrows)
# The new columns appear to be working correctly
```
### Figure 2: Outliers

```{r}
#Boxplot with the "sparrows"" data
box_plot <- sparrows %>%
  ggplot(aes(x = box_group, y = wingcrd)) + 
  geom_boxplot(width = 0.25) +
  labs(x = NULL,
       y = "Wing length (mm)")

box_plot
```

```{r}
#Range of values displayed on a Cleveland dot plot

cleveland_plot <- sparrows %>%
  ggplot(aes(x = wingcrd, y = row_order)) + 
  geom_point() + 
  labs(x = "Wing length (mm)", y = "Order of the data")

cleveland_plot
```

```{r}
# Both plots side by side

box_plot + cleveland_plot
```

```{r}

#Same as above with coordflip applied
box_plot + cleveland_plot + coord_flip()
```
### Figure 3: Outliers
```{r}
#Like the figure above, but with boxplot over th edot plot
box_plot + cleveland_plot + plot_layout(ncol = 1)
```

```{r}
#figure 3, 6 seperate variables displayed on one screen

p_culmen <- sparrows %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = culmen)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_nalospi <- sparrows%>%
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = nalospi)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_wt <- sparrows%>%
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = wt)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_wingcrd <- sparrows%>%
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = wingcrd)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_tarsus <- sparrows%>%
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = tarsus)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_head <- sparrows%>%
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = head)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

p_culmen + p_nalospi + p_wt + p_wingcrd + p_tarsus + p_head
```

### Figure 5: Distribution
```{r}
# Histogram
h1 <- sparrows %>%
  ggplot() +
  geom_histogram(aes(x = wt),
                 binwidth = 0.5, 
                 boundary = 0, 
                 closed = "right", 
                 color = "black"
                 ) +
  scale_x_continuous(breaks = seq(14, 28, by = 2))

# Faceted Histogram
h2 <- sparrows %>%
  filter(Month %in% 6:8) %>%
  mutate(Month = case_when(
    Month == 6 ~ "June",
    Month == 7 ~ "July",
    Month == 8 ~ "August"
  )) %>%
  ggplot() +
geom_histogram(aes(x = wt),
               binwidth = 0.5,
               boundary = 0,
               color = "black") +
  scale_x_continuous(breaks = seq(14, 28, by = 2)) +
  facet_wrap(~Month, ncol = 1)

h1 + h2

# (Personal note: scale_x_continuous() scales the x axis label)
```
### Figure 10: Relationships
```{r}
# GGally provides the ggscatmat function shown below
sparrows %>% ggscatmat(columns = 1:7)
```
### Figure 11



























